version: '2'
services:
    db:
        image: mariadb:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        image: php:7.1-fpm-alpine
        expose:
            - "9000"
        volumes:
            - .:/code
        links:
            - db
    web:
        image: nginx
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
