version: '2'
services:
    mysql:
        image: mariadb:10.2
        ports:
            - "3306:3306"
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
    php:
        build:
            context: .
        volumes:
            - .:/code
        environment:
            - SYMFONY_ENV
            - SYMFONY_DEBUG
            - APP_SECRET
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - DB_HOST
        links:
            - mysql
    web:
        image: nginx:1.13-alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
