version: '2'
services:
    db:
        image: mariadb:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build:
            context: .
        volumes:
            - .:/code
        environment:
            SYMFONY_ENV: dev
            SYMFONY_DEBUG: 1
            APP_SECRET: GenerateSecretHere
            DB_DRIVER: pdo_mysql
            DB_USER: symfony
            DB_PASSWORD: symfony
            DB_NAME: symfony
            DB_HOST: db
        links:
            - db
    web:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
