version: '2'
services:
    db:
        image: mariadb:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build:
            context: .
        volumes:
            - .:/code
        environment:
            SYMFONY_ENV: ${SYMFONY_ENV}
            SYMFONY_DEBUG: ${SYMFONY_DEBUG}
            APP_SECRET: ${APP_SECRET}
            DB_DRIVER: ${DB_DRIVER}
            DB_USER: ${MYSQL_USER}
            DB_PASSWORD: ${MYSQL_PASSWORD}
            DB_NAME: ${MYSQL_DATABASE}
            DB_HOST: ${DB_HOST}
        links:
            - db
    web:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
