parameters:
  env(APP_SECRET): NotSoSecretToken
  env(DB_DRIVER): pdo_sqlite
  env(DB_HOST): ~
  env(DB_PORT): ~
  env(DB_NAME): ~
  env(DB_USER): ~
  env(DB_PASSWORD): ~
  env(DB_PATH): ~
  locale: en

framework:
  default_locale: "%locale%"
  translator:
    fallback: "%locale%"
  secret: "%env(APP_SECRET)%"
  templating:
    engines: ['twig']

doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        driver:   "%env(DB_DRIVER)%"
        host:     "%env(DB_HOST)%"
        port:     "%env(DB_PORT)%"
        dbname:   "%env(DB_NAME)%"
        user:     "%env(DB_USER)%"
        password: "%env(DB_PASSWORD)%"
        path:     "%env(DB_PATH)%"
        charset: utf8mb4
        default_table_options:
          charset: utf8mb4
          collate: utf8mb4_unicode_ci
  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    mappings:
      - name: app
        is_bundle: false
        type: yml
        dir: "%kernel.root_dir%/Resources/config/doctrine"
        prefix: "App\\Entity"
