parameters:
  env(APP_SECRET): NotSoSecretToken
  env(DB_DRIVER): pdo_sqlite
  env(DB_HOST): ~
  env(DB_PORT): ~
  env(DB_NAME): ~
  env(DB_USER): ~
  env(DB_PASSWORD): ~
  env(DB_PATH): ~
  locale: en

framework:
  secret: "%env(APP_SECRET)%"

doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        driver:   "pdo_mysql"
        host:     "%env(DB_HOST)%"
        port:     "%env(DB_PORT)%"
        dbname:   "%env(MYSQL_DATABASE)%"
        user:     "%env(MYSQL_USER)%"
        password: "%env(MYSQL_PASSWORD)%"
        path:     "%env(DB_PATH)%"
        charset: utf8mb4
        default_table_options:
          charset: utf8mb4
          collate: utf8mb4_unicode_ci
        mapping_types:
          match_id: match_id
          ship_id: ship_id
          shot_id: shot_id
    types:
      match_id: App\Repository\Type\MatchIdType
      ship_id: App\Repository\Type\ShipIdType
      shot_id: App\Repository\Type\ShotIdType
  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    mappings:
      - name: app
        is_bundle: false
        type: yml
        dir: "%kernel.root_dir%/Resources/config/doctrine"
        prefix: "App\\Model"
