security:
  providers:
    match:
      id: app.match_provider
  firewalls:
    main:
      anonymous: ~
      guard:
        authenticators: ["app.jwt_authenticator"]
  access_control:
    - { path: ^/ship, roles: ROLE_PLAYER}
