services:
  app.lobby:
    class: App\Gameplay\Lobby
    arguments: ["@app.repository.match"]
  app.shipbuilder:
    class: App\Gameplay\Shipbuilder
    arguments: ["@app.repository.match"]
  app.combat:
    class: App\Gameplay\Combat
    arguments: ["@app.repository.match"]
  app.jwt:
    class: App\Security\Jwt
    arguments: ["%env(APP_SECRET)%"]
  app.findMatch:
    class: App\Service\FindMatchService
    arguments: ["@app.repository.match"]

  app.controller.match:
    class: App\Controller\MatchController
    arguments: ["@app.lobby", "@app.jwt", "@app.findMatch"]
  app.controller.ship:
    class: App\Controller\ShipController
    arguments: ["@app.findMatch", "@app.shipbuilder"]
  app.controller.shot:
    class: App\Controller\ShotController
    arguments: ["@app.combat"]

  app.repository.match:
    class: App\Repository\DoctrineMatchRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: ["App\\Model\\Match\\Match"]

  app.jwt_authenticator:
    class: App\Security\JwtAuthenticator
    arguments: ["@app.jwt"]
  app.match_provider:
    class: App\Security\MatchPlayerProvider
    arguments: ["@app.findMatch"]
